name: Test all script

on:
  push:
    branches: [ main, development, experimental, test* ]
  pull_request:
    branches: [ main, development, experimental, test* ]

jobs:

  build:
    name: Testing on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install HDF5 for pytables on macos-14
      if: ${{ matrix.runs-on == 'macos-latest' }}
      run: |
        brew install hdf5

    - name: Install & test package
      run: |
        python -m pip install --upgrade pip
        # pip install 'numpy<2.0.0' # due to lingering issues with other modules & numpy...

        pip install OSBModelValidation

        ./test_all.sh



    - name: Final version info
      run: |
          pip list
          env
